ControlFocus("Open","","Edit1")
Sleep(2000)
ControlSetText("Open","","Edit1","C:\FunctionalTestAutomationFramework\FinalNewProject\SupportingFiles\Braille Text.pdf")
Sleep(3000)
ControlClick("Open","","Button1")
Sleep(3000)
